### ISSUE TITLE
Sous categorie

### ISSUE THREAD

**Issue by Jireck-npds** [npds/npds-galerie#1]
Quel est l'interet de faire un sous-catégorie public ou membre alors que la restriction du parent est plus restreinte ?

**Comment by jipexu** [comment]
oui probablement une incohérence ... à voir

**Comment by Jireck-npds** [comment]
1 ans 6mois ....
Ca peux rester comme ca

**Comment by jipexu** [comment]
..ou pas ..

**Comment by jipexu** [comment]
donc au final l'idéal serait d'appliquer le système de droit QUE sur les galerie et non pas sur l'arborescence cat et sous cat car  ce qu'on veux protéger au final ce sont les images qui sont  donc directement dans les galeries ?
- Catégories pas de droits ?
- Sous Catégories pas de droits ?
- Galerie droits ?

**Comment by Jireck-npds** [comment]
si il faut gardé les droits,
Il faut juste checker si la catégorie du dessus est public ou privé.
Si elle est public on peux mettre des sous-cat ou galerie en privé ou public
Par contre si elle est privé les sous-cat ou galerie sont privé.

**Comment by jipexu** [comment]
oui vrai
les droits doivent dépendre des droits de leurs parents ... ce qui n'est vraiment pas le cas actuellement ...

**Comment by Jireck-npds** [comment]
Après comme dit plusieurs fois j'ai une version en full meta si ça intéresse. 
Cela permet de designer comme on veux tout

**Comment by jipexu** [comment]
> Quel est l'interet de faire un sous-catégorie public ou membre alors que la restriction du parent est plus restreinte ?

<= c'est implémenté (cohérence des droits parents enfants) reste juste une bricole dans l'interface admin et peut être dans les images aléatoires ...
