### ISSUE TITLE
Geolocalisation

### ISSUE THREAD

**Issue by Jireck-npds** [npds/npds-galerie#12]
Bonjour, 
Comment supprimer la Géolocalisation lors de la soumission d'images ?

Pourquoi on ne voit pas si on a soumis une image ==> aucun signe distinctif meme pas un titre?

**Comment by Jireck-npds** [comment]
<img width="462" alt="image" src="https://github.com/npds/npds-galerie/assets/16939826/cf82d409-63c8-4be1-991f-7c88fa59cbda">

**Comment by jipexu** [comment]
images proposé par qui admin ou utilisateur ? 
.... pour la géolocalisation tu n'as  juste qu'a pas t'en servir ...

**Comment by Jireck-npds** [comment]
par les 2 .
Le soucis étant d'avoir un affichage correct et simple.
Je vais m'expliquer plus avant : 
quand je soumet une image (en admin ou user);  j'ai : 
1) la géolocalisation qui mange plus de la moitié du cadre avec la carte.
2) une fois le fichier soumis aucun visuel qui me dit quel fichier est mis. cela est pour moi problématique.

pourquoi ne pas avoir un variable "$geloc" dans la conf de galerie afin d'afficher géoloc ou pas.
cela permettrait aux sites qui veulent géolocaliser d'avoir les elements et de mettre d'autres js ou. .. afin d'avoir un beau visuel et pour les autres justes un galerie.

un autocomplete pourrais aussi etre plus simple qu'un map 

genre https://github.com/solodev/address-auto-complete

**Comment by Jireck-npds** [comment]
pour le 2 une fois le fichier soumis aucun visuel qui me dit quel fichier est mis. cela est pour moi problématique.
le problème est réglé avec les soucis de bootstrap

pour le 1, je découvre le fonctionnement de la carte et vous donne mon avis 
- 1 les appareils photo 1, 2,3... sont mal initialisé (voir carte) , il serait bien de zoomer un peu plus sur la geoloc de base reperré
- 2 il serait bien mieux d'avoir comme dit au dessus un autocomplete ou d'avoir un bouton qui ouvre en popup la carte afin de géolocalisé la photo, ou de plus en plus dh'ebergeur support exif

<img width="456" alt="image" src="https://github.com/npds/npds-galerie/assets/16939826/800b69ae-e457-4ead-b6e4-b241df4c7aa7">

**Comment by jipexu** [comment]
tu as déjà un geocoder ... (la loupe) si tu entre une adresse alors la carte ira dans la zone avec les repères non encore géoreferencés ( ca permet d'aller rapidement dans une zone ...) (par contre un changement d'api récent provoque un bug - c'est corrigé sur le labo -) https://labo.infocapagde.com/viewtopic.php?topic=1666&forum=35

**Comment by Jireck-npds** [comment]
bon je clos ce sujet puisqu'on parle pas de ce qui est bloaquant pour moi
