### ISSUE TITLE
probleme de Hover

### ISSUE THREAD

**Issue by Jireck-npds** [npds/npds-galerie#13]
bonjour 
Il y a apparament un probleme de BR dans le Hover

<img width="311" alt="image" src="https://github.com/npds/npds-galerie/assets/16939826/572c029b-d5fb-48c7-9eeb-c7c81a807e87">

**Comment by jipexu** [comment]
idem ... version bs

**Comment by Jireck-npds** [comment]
par contre, pourquoi mettre le nom du fichier si la description est rempli
