### ISSUE TITLE
Arbo

### ISSUE THREAD

**Issue by Jireck-npds** [npds/npds-galerie#14]
l'arborescence dans l'admin ne se déplie pas 
probleme de collapse

 il y a le aria-checks alors que donc la doc du collapse il y a aria-controls https://getbootstrap.com/docs/5.0/components/collapse/

**Comment by jipexu** [comment]
ca fonctionne sur le labo... faut que je regarde si l'archive de galerie est bien a jour ... il faut que tu vois quelle version de BS tu as ....

**Comment by Jireck-npds** [comment]
comme tu le signale je pense qu'il y a un prbleme de version

**Comment by Jireck-npds** [comment]
https://github.com/npds/npds_dune/archive/refs/tags/v.16.3.zip
La version normalement validé et pas en cours de 2021

**Comment by jipexu** [comment]
il faut que tu prenne la version courante de npds et la version courante de td galerie ...
ton 16.3 est en bs 4.5 ton td galerie est pour bs 5.x c'est le prob

**Comment by Jireck-npds** [comment]
exact
