### ISSUE TITLE
formvalidation

### ISSUE THREAD

**Issue by Jireck-npds** [npds/npds-galerie#15]
<img width="1276" alt="image" src="https://github.com/npds/npds-galerie/assets/16939826/c9030a4a-726f-4123-b403-d0f6aec88aaa">

**Comment by jipexu** [comment]
a partir de quelle url ? 
tes scripts de formvalidation sont bien à jour ?

**Comment by Jireck-npds** [comment]
je ne vois pas pourquoi ils ne serait pas a jour comme dit dans l'autre issue c'est les archives officiels

**Comment by jipexu** [comment]
idem

**Comment by Jireck-npds** [comment]
ok
par contre cela me signale pour info
<img width="1246" alt="image" src="https://github.com/npds/npds-galerie/assets/16939826/d4297cce-aad4-4345-ad05-23219ab6a780">
