### ISSUE TITLE
declaration JS non valide

### ISSUE THREAD

**Issue by Jireck-npds** [npds/npds-galerie#16]
2 js declaré dans gal.php ne sont pas dans le core ou dans le module

<img width="524" alt="image" src="https://github.com/npds/npds-galerie/assets/16939826/98f28505-8c28-465c-9db8-54bdb087ec00">

**Comment by jipexu** [comment]
dans la version courante ces scripts sont bien la ... 
prends les ...dans une 16.3 il n'y étaient peut être pas ...

**Comment by Jireck-npds** [comment]
Ok dans la version courante peut etre mais cela lève 2 soucis : 
1) si ces libs ne sont utilisé que par npds_galerie pourquoi sont elles dans les lib du core ? 
2) La mise a jour des archives car j'ai pris uniquement les archives defini

**Comment by jipexu** [comment]
> Ok dans la version courante peut etre mais cela lève 2 soucis :
> 
> 1. si ces libs ne sont utilisé que par npds_galerie pourquoi sont elles dans les lib du core ?
> 2. La mise a jour des archives car j'ai pris uniquement les archives defini

1 car elles sont aussi utilisé dans le core !... 
2 prend la version courante de npds et la version courante de galerie (pas les releases ...)

**Comment by jipexu** [comment]
en d'autre terme ta version de galerie est en avance sur ton core (16.3) ....

**Comment by Jireck-npds** [comment]
OK, Je peux prendre cela mais ne serait il pas mieux de faire de nouvelles releases puisque celles-ci fonctionnent

**Comment by jipexu** [comment]
c'est prévu la 16.4 à l'automne je pense ...
